var Main = {
    init: function () {
        $("#captcha").css("background", "" + Settings.colors.color1)
        $("#colorspanel").css("background", "" + Settings.colors.color1)
        $("#dataadded").css("background", "" + Settings.colors.color1)
        $("#databasepanel").css("background", "" + Settings.colors.color1)
        $("#datadeleted").css("background", "" + Settings.colors.color1)
        $("#datadownloaded").css("background", "" + Settings.colors.color1)
        $("#hoursscreen").css("background", "" + Settings.colors.color1)
        $("#register").css("background", "" + Settings.colors.color1)
        $("#sethoursscreen").css("background", "" + Settings.colors.color1)
        $("#settingspanel").css("background", "" + Settings.colors.color1)
        $("#tablescreated").css("background", "" + Settings.colors.color1)
        $("#tablesdeleted").css("background", "" + Settings.colors.color1)
        $("#todayscreen").css("background", "" + Settings.colors.color1)
        $("#weekscreen").css("background", "" + Settings.colors.color1)
        $("body").css("color", "" + Settings.colors.color2)
        $("input").css("color", "" + Settings.colors.color2)
        $("body").css("background", "" + Settings.colors.color3)
        $("input").css("background", "" + Settings.colors.color3)
        $("#settings").css("background", "" + Settings.colors.color4)
        $("#today").css("background", "" + Settings.colors.color4)
        $("#week").css("background", "" + Settings.colors.color4)
        $("#sethoursinfo").css("color", "" + Settings.colors.color5)
        $("#captchaaccept").css("background", "" + Settings.colors.color6)
        $("#captchareload").css("background", "" + Settings.colors.color6)
        $("body").css("font-family", ""+Settings.font)
	}
};